"""changed respective_relevance to be nullable

Revision ID: 68f54f07edb5
Revises: c444c42d0177
Create Date: 2025-05-15 00:47:38.553468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f54f07edb5'
down_revision: Union[str, None] = 'c444c42d0177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filtered_match_in_news', 'respective_relevance',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filtered_match_in_news', 'respective_relevance',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
