"""Added pipeline status to match

Revision ID: 76a1a35c8f47
Revises: b8cd3826cfcc
Create Date: 2025-04-30 17:28:44.847845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a1a35c8f47'
down_revision: Union[str, None] = 'b8cd3826cfcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('pipeline_status', sa.Enum('NEW', 'SENT', 'PROCESSED', 'ERROR', name='pipelinestatus'), nullable=False))
    op.add_column('match', sa.Column('pipeline_update_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'pipeline_update_time')
    op.drop_column('match', 'pipeline_status')
    # ### end Alembic commands ###
