"""fixes

Revision ID: 8032e52dd316
Revises: 7c9330bb5839
Create Date: 2025-03-10 16:19:00.243368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8032e52dd316'
down_revision: Union[str, None] = '7c9330bb5839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_link')
    op.drop_table('player_link')
    op.add_column('match', sa.Column('sport_id', sa.Uuid(), nullable=False))
    op.add_column('match', sa.Column('tournament_url', sa.String(), nullable=True))
    op.add_column('match', sa.Column('external_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'match', ['external_id'])
    op.create_foreign_key(None, 'match', 'sport', ['sport_id'], ['sport_id'])
    op.add_column('team', sa.Column('team_url', sa.String(), nullable=True))
    op.add_column('team_member', sa.Column('team_member_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_member', 'team_member_url')
    op.drop_column('team', 'team_url')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='unique')
    op.drop_column('match', 'external_id')
    op.drop_column('match', 'tournament_url')
    op.drop_column('match', 'sport_id')
    op.create_table('player_link',
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('link', name='player_link_pkey')
    )
    op.create_table('team_link',
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('link', name='team_link_pkey')
    )
    # ### end Alembic commands ###
